name: Create release
on:
  push:
    tags:
      - v*

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

env:
  prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') }}
  KSP: ${{ secrets.KSP }}

jobs:
  build:
    name: Create release
    permissions:
      contents: write
      discussions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4

      - name: Building
        run: |
         chmod +x gradlew
         ./gradlew app:assembleRelease
      - name: Signing
        run: |
         java -jar apksign.jar --apks app/build/outputs/apk/release --ks android.keystore --ksAlias key  --ksKeyPass "$KSP" --ksPass "$KSP" --out app/build/outputs/apk/release
         mv app/build/outputs/apk/release/app-release-aligned-signed.apk app/build/outputs/apk/release/release.apk
         echo "VERSION="$(date +"%y%m%d%H")"" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ env.prerelease }}
          files: app/build/outputs/apk/release/*.apk
          fail_on_unmatched_files: true
          generate_release_notes: true
